all:
  children:
    mac:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /opt/homebrew/bin/python3
    ubuntu:
      hosts:
        ubuntu-desktop:
          ansible_host: x.x.x.x
          ansible_user: akdpubuntu
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3
