lazygit_version: "0.44.1"
neovim_version: "0.11.3"
nerd_font_name: "JetBrainsMono"
nerd_font_version: "v3.2.1"
fastfetch_version: "2.27.0"
kind_version: "0.32.0"
kubectl_version: "1.36.1"
helm_version: "4.2.0"
helmfile_version: "1.5.2"
k9s_version: "0.50.18"
uv_version: "0.11.19"
claude_code_version: "2.1.167"
